# Generated by Django 2.0.3 on 2018-03-22 17:50
# Migrations was edited bc validate_no_nums was removed
# from model which resulted in an undefined error
from django.db import migrations, models
import projects.models


def validate_no_nums(value):
    if value.isdigit():
        raise ValidationError(
            _('%(value)s has a number'),
            params={'value': value},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180322_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=120, validators=[validate_no_nums]),
        ),
    ]
