# Generated by Django 2.0.3 on 2018-03-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180322_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='num',
        ),
    ]
