# Generated by Django 2.0.3 on 2018-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180322_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='industry',
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.ManyToManyField(to='projects.Industry'),
        ),
    ]
