# Generated by Django 2.0.3 on 2018-03-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180326_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Foo'},
        ),
    ]
