# Generated by Django 2.0.3 on 2018-03-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180326_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={},
        ),
    ]
