# Generated by Django 2.0.3 on 2018-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20180326_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
