# Generated by Django 2.0.3 on 2018-04-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_isfeatured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isFeatured',
            field=models.BooleanField(default=False, help_text='Hello'),
        ),
    ]
